### ISSUE TITLE
IPFS Companion cannot handle a ? in the title of a document.

### ISSUE THREAD

**Issue by ctrlcctrlv** [ipfs/ipfs-companion#1201]
**Describe the bug**
* Files such as e.g. https://mindwar.net/Jim%20Stewartson%20v.%20QAnon%20%E2%80%94%20Can%20you%20spot%20the%20difference%3F.pdf result in [the following erroneous HTTP session](https://github.com/ipfs/ipfs-companion/files/11497121/mindwar.net.ipns.localhost.har.zip):

```yaml
301 GET https://mindwar.net/Jim%20Stewartson%20v.%20QAnon%20%E2%80%94%20Can%20you%20spot%20the%20difference%3F.pdf
    Request headers
    Response headers (status = 301)
        Accept-Ranges: bytes
        Access-Control-Allow-Headers: Content-Type
        Access-Control-Allow-Headers: Range
        Access-Control-Allow-Headers: User-Agent
        Access-Control-Allow-Headers: X-Requested-With
        Access-Control-Allow-Methods: GET
        Access-Control-Allow-Origin: *
        Access-Control-Expose-Headers: Content-Length
        Access-Control-Expose-Headers: Content-Range
        Access-Control-Expose-Headers: X-Chunked-Output
        Access-Control-Expose-Headers: X-Ipfs-Path
        Access-Control-Expose-Headers: X-Ipfs-Roots
        Access-Control-Expose-Headers: X-Stream-Output
        Content-Length: 180941
        Content-Type: application/pdf
        Date: Wed, 17 May 2023 10:18:16 GMT
        Etag: "QmXZdegY4BBHdjMeCadhCbciziQTFynkApbgtDGbodhsz3"
        Last-Modified: Wed, 17 May 2023 10:18:16 GMT
        Location: http://mindwar.net.ipns.localhost:8080/Jim%20Stewartson%20v.%20QAnon%20%E2%80%94%20Can%20you%20spot%20the%20difference?.pdf
        X-DNS-Prefetch-Control: off
        X-Ipfs-Path: /ipns/mindwar.net/Jim Stewartson v. QAnon â Can you spot the difference?.pdf
        X-Ipfs-Roots: QmV7UhgGn2qULg9Wwz76if557XrwDbrSkxQGmhtya77a7R,QmXZdegY4BBHdjMeCadhCbciziQTFynkApbgtDGbodhsz3

404 GET http://localhost:8080/ipns/mindwar.net/Jim%20Stewartson%20v.%20QAnon%20%E2%80%94%20Can%20you%20spot%20the%20difference%3F.pdf
    Request headers
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q
                =0.7
        Accept-Encoding: gzip, deflate, br
        Accept-Language: en-US,en;q=0.9,es-419;q=0.8,es;q=0.7
        Connection: keep-alive
        DNT: 1
        Host: mindwar.net.ipns.localhost:8080
        Sec-Fetch-Dest: document
        Sec-Fetch-Mode: navigate
        Sec-Fetch-Site: none
        Sec-Fetch-User: ?1
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
        sec-ch-ua: "Not:A-Brand";v="99", "Chromium";v="112"
        sec-ch-ua-mobile: ?0
        sec-ch-ua-platform: "Linux"
    Response headers (status = 404)
        Access-Control-Allow-Headers: Content-Type
        Access-Control-Allow-Headers: Range
        Access-Control-Allow-Headers: User-Agent
        Access-Control-Allow-Headers: X-Requested-With
        Access-Control-Allow-Methods: GET
        Access-Control-Allow-Origin: *
        Access-Control-Expose-Headers: Content-Length
        Access-Control-Expose-Headers: Content-Range
        Access-Control-Expose-Headers: X-Chunked-Output
        Access-Control-Expose-Headers: X-Ipfs-Path
        Access-Control-Expose-Headers: X-Ipfs-Roots
        Access-Control-Expose-Headers: X-Stream-Output
        Content-Length: 221
        Content-Type: text/plain; charset=utf-8
        Date: Wed, 17 May 2023 10:38:01 GMT
        X-Content-Type-Options: nosniff
        X-Ipfs-Path: /ipns/mindwar.net/Jim Stewartson v. QAnon â Can you spot the difference

404 GET http://mindwar.net.ipns.localhost:8080/Jim%20Stewartson%20v.%20QAnon%20%E2%80%94%20Can%20you%20spot%20the%20difference?.pdf
    Request headers
        DNT: 1
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
        sec-ch-ua: "Not:A-Brand";v="99", "Chromium";v="112"
        sec-ch-ua-mobile: ?0
        sec-ch-ua-platform: "Linux"
    Response headers (status = 404)
        Access-Control-Allow-Headers: Content-Type
        Access-Control-Allow-Headers: Range
        Access-Control-Allow-Headers: User-Agent
        Access-Control-Allow-Headers: X-Requested-With
        Access-Control-Allow-Methods: GET
        Access-Control-Allow-Origin: *
        Access-Control-Expose-Headers: Content-Length
        Access-Control-Expose-Headers: Content-Range
        Access-Control-Expose-Headers: X-Chunked-Output
        Access-Control-Expose-Headers: X-Ipfs-Path
        Access-Control-Expose-Headers: X-Ipfs-Roots
        Access-Control-Expose-Headers: X-Stream-Output
        Content-Length: 221
        Content-Type: text/plain; charset=utf-8
        Date: Wed, 17 May 2023 10:38:01 GMT
        X-Content-Type-Options: nosniff
        X-DNS-Prefetch-Control: off
        X-Ipfs-Path: /ipns/mindwar.net/Jim Stewartson v. QAnon — Can you spot the difference
```

IPFS Companion incorrectly converts `%3F` to `?`.

**To Reproduce**
1. Self evident.

**Expected behavior**
Self-evident.

kubo itself is fully capable of resolving `/ipns/mindwar.net/Jim%20Stewartson%20v.%20QAnon%20%E2%80%94%20Can%20you%20spot%20the%20difference%3F.pdf` to QmXZdegY4BBHdjMeCadhCbciziQTFynkApbgtDGbodhsz3.

```
$ ipfs get --progress=0 "$(ipfs resolve /ipns/mindwar.net/'Jim Stewartson v. QAnon — Can you spot the difference?.pdf')"
Saving file(s) to QmXZdegY4BBHdjMeCadhCbciziQTFynkApbgtDGbodhsz3
```

But perhaps is the cause of the bug because note its Location return here:

```bash
$ curl --head 'localhost:8080/ipns/mindwar.net/Jim%20Stewartson%20v.%20QAnon%20%E2%80%94%20Can%20you%20spot%20the%20difference%3F.pdf'
```
```http
HTTP/1.1 301 Moved Permanently
Accept-Ranges: bytes
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Headers: Range
Access-Control-Allow-Headers: User-Agent
Access-Control-Allow-Headers: X-Requested-With
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Length
Access-Control-Expose-Headers: Content-Range
Access-Control-Expose-Headers: X-Chunked-Output
Access-Control-Expose-Headers: X-Ipfs-Path
Access-Control-Expose-Headers: X-Ipfs-Roots
Access-Control-Expose-Headers: X-Stream-Output
Content-Length: 180941
Content-Type: application/pdf
Etag: "QmXZdegY4BBHdjMeCadhCbciziQTFynkApbgtDGbodhsz3"
Last-Modified: Wed, 17 May 2023 11:00:40 GMT
Location: http://mindwar.net.ipns.localhost:8080/Jim%20Stewartson%20v.%20QAnon%20%E2%80%94%20Can%20you%20spot%20the%20difference?.pdf
X-Ipfs-Path: /ipns/mindwar.net/Jim Stewartson v. QAnon — Can you spot the difference?.pdf
X-Ipfs-Roots: QmV7UhgGn2qULg9Wwz76if557XrwDbrSkxQGmhtya77a7R,QmXZdegY4BBHdjMeCadhCbciziQTFynkApbgtDGbodhsz3
Date: Wed, 17 May 2023 11:00:40 GMT
```

I'll report up there too.

**Screenshots**
![image](https://github.com/ipfs/ipfs-companion/assets/838783/a4b7e166-1f3a-4fac-b9d1-f3fed0b137f2)

**Desktop (please complete the following information):**
 - OS: Linux debutanuki 6.3.2-zen1-1-zen #​1 ZEN SMP PREEMPT_DYNAMIC Thu, 11 May 2023 16:40:19 +0000 x86_64 GNU/Linux
 - Browser: ungoogled-chromium-bin 112.0.5615.165-1
 - Version: 2.22.1

**Smartphone (please complete the following information):**
N/A.
